server:
  port: 8000
  servlet:
    context-path: /api
debug: false
spring:
  application:
    name: online-book-store-application
  datasource:
    url: jdbc:h2:mem:library
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
